import 'package:auto_route/auto_route.dart';

import 'app_router.gr.dart';

@AutoRouterConfig()
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    AutoRoute(page: MyHomeRoute.page, path: '/'),
    AutoRoute(page: UserListRoute.page, path: '/users'),
    AutoRoute(page: UserDetailRoute.page, path: '/user/:id'),
    AutoRoute(page: RebuildDemoRoute.page, path: '/rebuild-demo'),
    AutoRoute(page: BlocBasicsRoute.page, path: '/bloc-basics'),
    AutoRoute(page: BlocListRoute.page, path: '/bloc-list'),
    AutoRoute(page: PostDetailRoute.page, path: '/post-detail'),
    AutoRoute(page: AutoRouteHomeRoute.page, path: '/auto-route'),
    AutoRoute(page: NoParamRoute.page, path: '/auto-route/no-param'),
    AutoRoute(page: WithParamRoute.page, path: '/auto-route/with-param/:id'),
    AutoRoute(page: ReturnValueRoute.page, path: '/auto-route/return-value'),
    AutoRoute(page: WithCallbackRoute.page, path: '/auto-route/with-callback'),
    AutoRoute(page: FlavorsDemoRoute.page, path: '/flavors'),
    AutoRoute(page: WidgetTestDemoRoute.page, path: '/widget-test'),
    AutoRoute(page: IntegrationTestDemoRoute.page, path: '/integration-test'),
    AutoRoute(page: ThemeDemoRoute.page, path: '/theme'),
    AutoRoute(page: L10nDemoRoute.page, path: '/l10n'),
    AutoRoute(page: InheritedWidgetDemoRoute.page, path: '/inherited-widget'),
    AutoRoute(page: InheritedWidgetNotifierRoute.page, path: '/inherited-widget-notifier'),
    AutoRoute(page: MultiListenerRoute.page, path: '/multi-listener'),
    AutoRoute(page: ProviderBasicRoute.page, path: '/provider-basic'),
    AutoRoute(page: ProviderMultiRoute.page, path: '/provider-multi'),
    AutoRoute(page: ProviderAsyncRoute.page, path: '/provider-async'),
    AutoRoute(page: ProviderOptimizationRoute.page, path: '/provider-optimization'),
    AutoRoute(page: ProviderCartRoute.page, path: '/provider-cart'),

    // Riverpod 学习路径
    AutoRoute(page: RiverpodHubRoute.page, path: '/riverpod-hub'),
    AutoRoute(page: RiverpodHelloRoute.page, path: '/test-riverpod/hello'),
    AutoRoute(page: RiverpodProvidersRoute.page, path: '/test-riverpod/providers'),
    AutoRoute(page: RiverpodStateNotifierRoute.page, path: '/test-riverpod/state-notifier'),
    AutoRoute(page: RiverpodConsumerRoute.page, path: '/test-riverpod/consumer'),
    AutoRoute(page: FamilyDemoRoute.page, path: '/test-riverpod/family'),
    AutoRoute(page: RiverpodAutoDisposeRoute.page, path: '/test-riverpod/auto-dispose'),
    AutoRoute(page: RiverpodDependencyRoute.page, path: '/test-riverpod/dependency'),
    AutoRoute(page: RiverpodOptimizationRoute.page, path: '/test-riverpod/optimization'),
    AutoRoute(page: AsyncValueRoute.page, path: '/test-riverpod/async-value'),
    AutoRoute(page: RiverpodScopedRoute.page, path: '/test-riverpod/scoped'),
    AutoRoute(page: RefreshDemoRoute.page, path: '/test-riverpod/refresh'),
    AutoRoute(page: TodoRoute.page, path: '/test-riverpod/todo'),

    // HTTP 学习路径
    AutoRoute(page: TestHttpsRoute.page, path: '/test-https'),
    AutoRoute(page: HttpBasicRoute.page, path: '/test-https/basic'),
    AutoRoute(page: HttpPackageDemoRoute.page, path: '/test-https/http-package'),
    AutoRoute(page: DioBasicDemoRoute.page, path: '/test-https/dio-basic'),
    AutoRoute(page: DioInterceptorDemoRoute.page, path: '/test-https/dio-interceptor'),
    AutoRoute(page: DioAdvancedConfigRoute.page, path: '/test-https/dio-advanced'),
    AutoRoute(page: FileUploadDownloadDemoRoute.page, path: '/test-https/file-upload-download'),
    AutoRoute(page: DioClientDemoRoute.page, path: '/test-https/dio-client'),
    AutoRoute(page: CacheStrategyDemoRoute.page, path: '/test-https/cache-strategy'),
    AutoRoute(page: NetworkStateDemoRoute.page, path: '/test-https/network-state'),
    AutoRoute(page: AuthSecurityDemoRoute.page, path: '/test-https/auth-security'),
    AutoRoute(page: WebSocketDemoRoute.page, path: '/test-https/websocket'),
    AutoRoute(page: GraphQLDemoRoute.page, path: '/test-https/graphql'),
    AutoRoute(page: PerfOptimizationRoute.page, path: '/test-https/perf'),
    AutoRoute(page: RequestDebounceRoute.page, path: '/test-https/perf/debounce'),
    AutoRoute(page: PaginationDemoRoute.page, path: '/test-https/perf/pagination'),
    AutoRoute(page: ChunkedUploadDemoRoute.page, path: '/test-https/perf/chunked-upload'),
    AutoRoute(page: IsolateParseDemoRoute.page, path: '/test-https/perf/isolate'),
    AutoRoute(page: HttpTestDemoRoute.page, path: '/test-https/test'),
    AutoRoute(page: ArchDemoRoute.page, path: '/test-https/arch'),

    // 异步编程学习路径
    AutoRoute(page: AsyncHubRoute.page, path: '/async-hub'),
    AutoRoute(page: EventLoopBasicsRoute.page, path: '/async/event-loop'),
    AutoRoute(page: MicrotaskQueueRoute.page, path: '/async/microtask'),
    AutoRoute(page: ExecutionOrderRoute.page, path: '/async/execution-order'),
    AutoRoute(page: FutureBasicsRoute.page, path: '/async/future-basics'),
    AutoRoute(page: AsyncAwaitRoute.page, path: '/async/async-await'),
    AutoRoute(page: FutureChainRoute.page, path: '/async/future-chain'),
    AutoRoute(page: FutureCombinatorsRoute.page, path: '/async/future-combinators'),
    AutoRoute(page: FutureErrorHandlingRoute.page, path: '/async/error-handling'),
    AutoRoute(page: StreamBasicsRoute.page, path: '/async/stream-basics'),
    AutoRoute(page: StreamTypesRoute.page, path: '/async/stream-types'),
    AutoRoute(page: StreamControllerRoute.page, path: '/async/stream-controller'),
    AutoRoute(page: StreamOperatorsRoute.page, path: '/async/stream-operators'),
    AutoRoute(page: AsyncGeneratorRoute.page, path: '/async/async-generator'),
    AutoRoute(page: StreamTransformerRoute.page, path: '/async/stream-transformer'),
    AutoRoute(page: StreamMergeSplitRoute.page, path: '/async/stream-merge-split'),
    AutoRoute(page: BackpressureRoute.page, path: '/async/backpressure'),

    // 事件传递机制学习路径
    AutoRoute(page: EventHubRoute.page, path: '/event-mechanism'),
    AutoRoute(page: PointerEventsRoute.page, path: '/event-mechanism/pointer'),
    AutoRoute(page: GestureRecognizersRoute.page, path: '/event-mechanism/gesture'),
    AutoRoute(page: GestureArenaRoute.page, path: '/event-mechanism/arena'),
    AutoRoute(page: HitTestingRoute.page, path: '/event-mechanism/hit-testing'),
    AutoRoute(page: EventDispatchRoute.page, path: '/event-mechanism/dispatch'),
    AutoRoute(page: NotificationDemoRoute.page, path: '/event-mechanism/notification'),
    AutoRoute(page: InheritedWidgetEventDemoRoute.page, path: '/event-mechanism/inherited'),
    AutoRoute(page: FocusKeyboardDemoRoute.page, path: '/event-mechanism/focus-keyboard'),
    AutoRoute(page: EventDebuggingDemoRoute.page, path: '/event-mechanism/debugging'),
  ];
}
